Repository jenkinsci/lib-access-modifier, pull requests merged in 2020-12, with the labels that each got.

#32 Use jenkins pom + modernise (spotbugs) and add CI
  Jenkinsfile
  access-modifier-annotation/pom.xml
  access-modifier-annotation/src/main/java/org/kohsuke/accmod/restrictions/ProtectedExternally.java
  access-modifier-checker/pom.xml
  access-modifier-checker/src/main/java/org/kohsuke/accmod/impl/Checker.java
  access-modifier-checker/src/main/java/org/kohsuke/accmod/impl/EnforcerMojo.java
  access-modifier-checker/src/main/java/org/kohsuke/accmod/impl/Restrictions.java
  pom.xml
  src/spotbugs/excludesFilter.xml
Labels: chore

#34 Initial metadata updates - dependabot, release-drafter etc
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  LICENSE.md
  README.md
Labels: chore

#33 Incrementalified.
  .mvn/extensions.xml
  .mvn/maven.config
  access-modifier-annotation/pom.xml
  access-modifier-checker/pom.xml
  access-modifier-suppressions/pom.xml
  pom.xml
Labels: chore

#38 Use junit from pom
  access-modifier-annotation/pom.xml
  access-modifier-checker/pom.xml
Labels: dependencies

#17 Classes should be able to access their own fields and methods
  access-modifier-checker/src/it/own-members/invoker.properties
  access-modifier-checker/src/it/own-members/pom.xml
  access-modifier-checker/src/it/own-members/src/main/java/Outer.java
  access-modifier-checker/src/it/own-members/src/main/java/SomeClass.java
  access-modifier-checker/src/main/java/org/kohsuke/accmod/impl/Checker.java
Labels: enhancement

#39 Output invoker failures in junit format
  access-modifier-checker/pom.xml
Labels: chore

#42 Set url so releases are sourced properly
  pom.xml
Labels: chore
